### ISSUE TITLE
Streaming has stopped

### ISSUE THREAD

**Issue by mthornton05** [techiejohn/Csatornak#1]
Hi there,
Thanks for your hard work on this plug-in. It's been working great for a while but then the streams stopped (all channels are affected).

If it's possible to get it running again it would be really great.

Thanks!
Matt

**Comment by IslandJohn** [comment]
This should be fixed now. It's been fixed for a while but the old URLs continued to work on and off so I forgot about committing the update.

**Comment by mthornton05** [comment]
Thanks so much! Working great now. I really appreciate it.

All the best,
Matt
